force-app/main/default/objects/Trip__c/Trip__c.object-meta.xml
<CustomObject>
    <label>Trip</label>
    <nameField>
        <displayFormat>Voyage-{0000}</displayFormat>
        <label>Trip Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Annulé</fullName>
            </value>
            <value>
                <fullName>A venir</fullName>
            </value>
            <value>
                <fullName>En cours</fullName>
            </value>
            <value>
                <fullName>Terminé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TripSelector.cls
public with sharing class TripSelector {
    public static Trip__c getById(Id tripId) {
        try {
            Trip__c trip = [SELECT Id, Name, Status__c FROM Trip__c WHERE Id = :tripId  WITH SECURITY_ENFORCED LIMIT 1];
            if (trip == null) {
                System.debug('Access denied or ou no data available!');
            }
            return trip;
        } catch (SecurityException e) {
            System.debug('Security error : ' + e.getMessage());
            return null;
        }
    }

    public static List<Trip__c> getAll() {
        try {
            List<Trip__c> trips = [SELECT Id, Name, Status__c FROM Trip__c WITH SECURITY_ENFORCED];
            System.debug(trips.isEmpty() ? 'Access denied or ou no data available' : trips.size() + ' voyages found');
            return trips;
        } catch (Exception e) {
            System.debug('Security error : ' + e.getMessage());
            return new List<Trip__c>();
        }
    }
}