force-app/main/default/objects/Trip__c/Trip__c.object-meta.xml
<CustomObject>
    <label>Trip</label>
    <nameField>
        <displayFormat>Voyage-{0000}</displayFormat>
        <label>Trip Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Annulé</fullName>
            </value>
            <value>
                <fullName>A venir</fullName>
            </value>
            <value>
                <fullName>En cours</fullName>
            </value>
            <value>
                <fullName>Terminé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CancelTripsBatch.cls
global class CancelTripsBatch implements Database.Batchable<sObject> ,Schedulable{
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator([
            SELECT Id, Number_of_Participants__c 
            FROM Trip__c 
            WHERE Start_Date__c = :Date.today().addDays(7)
            AND Number_of_Participants__c < 10
            AND Number_of_Participants__c != null
            AND Status__c != 'Annulé'
        ]);
    }
    
    global void execute(Database.BatchableContext BC, List<Trip__c> trips) {
        for (Trip__c trip : trips) {
            trip.Status__c = 'Annulé';
        }
        
        update trips;
    }
    //to schedule
    global void execute(SchedulableContext sc) {
        CancelTripsBatch batch = new CancelTripsBatch();
        Database.executeBatch(batch);
    }
    global void finish(Database.BatchableContext BC) {
    }
}